name: 'docker-gcr-action'
description: 'Provides login for docker process to publish to Google Cloud Container Registry'
inputs:
  SERVICE_ACCOUNT_KEY:
    description: 'Google Service Account key in JSON format'
    required: true
  HOST:
    description: 'GCR host to log into. Defaults to gcr.io'
    required: true
    default: 'gcr.io'
branding:
  icon: unlock
  color: gray-dark
runs:
  using: node12
  main: 'dist/index.js'